In [10]:
import cv2
image = cv2.imread('pic53.png') # reading the image
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) # convert2grayscale
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU) # convert2binary
smallbin=cv2.resize(binary,(720,960))
cv2.imshow('binary',smallbin)
#cv2.imwrite('binary.png', binary)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
 contours, _ = cv2.findContours(~binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE) 
# find contours
for contour in contours:
    """
    draw a rectangle around those contours on main image
    """
    [x,y,w,h] = cv2.boundingRect(contour)
    cv2.rectangle(image, (x,y), (x+w,y+h), (0, 255, 0), 1)
smallim=cv2.resize(image,(720,960))
cv2.imshow('contour',smallim)
#cv2.imwrite('contours.png', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
import numpy as np
mask = np.ones(image.shape[:2], dtype="uint8")* 255 # create blank image of same dimension of the original image
contours, _= cv2.findContours(~binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE) 
heights = [cv2.boundingRect(contour)[3] for contour in contours] # collecting heights of each contour
avgheight = sum(heights)/len(heights) # average height
# finding the larger contours
# Applying Height heuristic
for c in contours:
    [x,y,w,h] = cv2.boundingRect(c)
    if h > 2*avgheight and h<10*avgheight:
        cv2.drawContours(mask, [c], -1, 0, -1)

smallmask=cv2.resize(mask,(720,960))
cv2.imshow('filter', smallmask)
#cv2.imwrite('filter.png', mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [67]:
mask1=mask.copy()
for c in contours:
    [x,y,w,h] = cv2.boundingRect(c)
    if h > 2*avgheight and h<10*avgheight:
        d=np.array([[[x,y],[x,y+h],[x+w,y+h],[x+w,y]]])
        cv2.drawContours(mask1, [d], -1, 0, -1)
smallmask1=cv2.resize(mask1,(720,960))
cv2.imshow('filter', smallmask1)
#cv2.imwrite('filter.png', mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [68]:
color = cv2.cvtColor(mask1, cv2.COLOR_GRAY2BGR)
image1 = cv2.imread('/home/madhan/EE04_Tess/newspaper/news3.png') # reading the image

head=cv2.add(image1,color)
smallhead=cv2.resize(head,(720,960))
cv2.imshow('headings', smallhead)
cv2.imwrite("/home/madhan/EE04_Tess/newspaper/news3h.png", head)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
image.shape

(6622, 4167, 3)

In [29]:
import numpy as np
import cv2
image = cv2.imread('/home/madhan/EE04_Tess/newspaper/news3.png') # reading the image
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) # convert2grayscale
thresh, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU) # convert2binary
contours, _ = cv2.findContours(~binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE) 
# find contours
for contour in contours:
    """
    draw a rectangle around those contours on main image
    """
    [x,y,w,h] = cv2.boundingRect(contour)
    cv2.rectangle(image, (x,y), (x+w,y+h), (0, 255, 0), 1)

mask = np.ones(image.shape[:2], dtype="uint8")* 255 # create blank image of same dimension of the original image
contours, _= cv2.findContours(~binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE) 
heights = [cv2.boundingRect(contour)[3] for contour in contours] # collecting heights of each contour
avgheight = sum(heights)/len(heights) # average height
# finding the larger contours
# Applying Height heuristic
for c in contours:
    [x,y,w,h] = cv2.boundingRect(c)
    if h > 2*avgheight:
        cv2.drawContours(mask, [c], -1, 0, -1)
mask1=mask.copy()
for c in contours:
    [x,y,w,h] = cv2.boundingRect(c)
    if h > 2*avgheight:
        d=np.array([[[x,y],[x,y+h],[x+w,y+h],[x+w,y]]])
        cv2.drawContours(mask1, [d], -1, 0, -1)
color = cv2.cvtColor(mask1, cv2.COLOR_GRAY2BGR)
image1 = cv2.imread('/home/madhan/EE04_Tess/newspaper/news3.png') # reading the image

head=cv2.add(image1,color)
cv2.imwrite("/home/madhan/EE04_Tess/newspaper/news3h.png", head)

True

In [8]:
contours

[array([[[   2, 1244]],
 
        [[   3, 1244]]], dtype=int32),
 array([[[  50, 1213]]], dtype=int32),
 array([[[   3, 1142]]], dtype=int32),
 array([[[   3, 1116]],
 
        [[   4, 1116]]], dtype=int32),
 array([[[   6, 1115]],
 
        [[   7, 1115]]], dtype=int32),
 array([[[  7, 983]]], dtype=int32),
 array([[[ 10, 981]],
 
        [[ 11, 981]]], dtype=int32),
 array([[[  4, 969]],
 
        [[  3, 970]],
 
        [[  2, 970]],
 
        [[  4, 970]],
 
        [[  5, 969]]], dtype=int32),
 array([[[  8, 963]],
 
        [[  7, 964]],
 
        [[  8, 964]],
 
        [[  9, 963]]], dtype=int32),
 array([[[  2, 906]],
 
        [[  1, 907]],
 
        [[  1, 908]],
 
        [[  2, 907]],
 
        [[  3, 907]],
 
        [[  4, 906]],
 
        [[  5, 907]],
 
        [[  6, 906]],
 
        [[  7, 906]]], dtype=int32),
 array([[[  9, 899]],
 
        [[  8, 900]],
 
        [[  7, 900]],
 
        [[  7, 901]],
 
        [[  9, 899]],
 
        [[ 10, 899]]], dtype=int32),
 