In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
import cv2
import numpy as np
import os

def transform(pos):
	pts=[]
	n=len(pos)
	for i in range(n):
		pts.append(list(pos[i][0]))
	#print pts
	sums={}
	diffs={}
	for i in pts:
		x=i[0]
		y=i[1]
		sum=x+y
		diff=y-x
		sums[sum]=i
		diffs[diff]=i
	sums=sorted(sums.items())
	diffs=sorted(diffs.items())
	n=len(sums)
	rect=[sums[0][1],diffs[0][1],diffs[n-1][1],sums[n-1][1]]
	#	   top-left   top-right   bottom-left   bottom-right
	
	h1=np.sqrt((rect[0][0]-rect[2][0])**2 + (rect[0][1]-rect[2][1])**2)		#height of left side
	h2=np.sqrt((rect[1][0]-rect[3][0])**2 + (rect[1][1]-rect[3][1])**2)		#height of right side
	h=max(h1,h2)
	
	w1=np.sqrt((rect[0][0]-rect[1][0])**2 + (rect[0][1]-rect[1][1])**2)		#width of upper side
	w2=np.sqrt((rect[2][0]-rect[3][0])**2 + (rect[2][1]-rect[3][1])**2)		#width of lower side
	w=max(w1,w2)
	
	#print '#',rect
	return int(w),int(h),rect
def sizee(arr):
    c=0
    pts=np.zeros(8)
    for i in np.ravel(arr):
        pts[c]=int(i/r)
        c+=1
    return np.float32([[pts[0],pts[1]],[pts[2],pts[3]],[pts[4],pts[5]],[pts[6],pts[7]]])
img=cv2.imread('/home/madhan/EE04_Tess/final/book.png')
x=img.shape[1]
y=img.shape[0]
r=500.0 / img.shape[1]
dim=(500, int(img.shape[0] * r))
img1=cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
gray=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
gray=cv2.GaussianBlur(gray,(7,5),0)
edge=cv2.Canny(gray,100,200)

kernel = np.ones((5,5))
edge = cv2.dilate(edge, kernel, iterations = 1)
edge = cv2.dilate(edge, kernel, iterations = 1)

contours,_=cv2.findContours(edge.copy(),1,1)
n=len(contours)
max_area=0
pos=0
for i in contours:
	area=cv2.contourArea(i)
	if area>max_area:
		max_area=area
		pos=i
peri=cv2.arcLength(pos,True)
approx=cv2.approxPolyDP(pos,0.02*peri,True)

size=img.shape

cv2.imshow("edge",edge)
cv2.waitKey(0)
cv2.destroyAllWindows()

#cv2.imwrite("pic27re.jpg",img)
w,h,arr=transform(approx)

pts1=np.float32(arr)
pts2=np.float32([[0,0],[x,0],[0,y],[x,y]])
#pts1=np.float32(arr)
#pts2=sizee(pts2)
if cv2.contourArea(pos)<(0.125*(x*r)*(y*r)):
    pts1=pts2
else:
    pts1=sizee(pts1)
#pts1=np.float32(arr)
#pts2=sizee(pts2)

M=cv2.getPerspectiveTransform(pts1,pts2)
dst=cv2.warpPerspective(img,M,(x,y))
#image=cv2.cvtColor(dst,cv2.COLOR_BGR2GRAY)
#image=cv2.adaptiveThreshold(image,255,1,0,11,2)
#image = cv2.resize(image,(int(w/r),int(h/r)),interpolation = cv2.INTER_AREA)
cv2.imwrite("result1.jpg",dst)

#cv2.imshow("dst",dst)
cv2.imshow("edge",edge)

cv2.waitKey(0)
cv2.destroyAllWindows()
#print(cv2.imwrite("result.jpg",dst))

In [11]:
pos

array([[[344, 296]],

       [[343, 297]],

       [[342, 297]],

       ...,

       [[347, 296]],

       [[346, 296]],

       [[345, 296]]], dtype=int32)

In [25]:
(0.25*(x*r)*(y*r))

35156.25

In [4]:
def auto_canny(image, sigma=0.33):
	# compute the median of the single channel pixel intensities
	v = np.median(image)

	# apply automatic Canny edge detection using the computed median
	lower = int(max(0, (1.0 - sigma) * v))
	upper = int(min(255, (1.0 + sigma) * v))
	edged = cv2.Canny(image, lower, upper)

	# return the edged image
	return edged

In [36]:
dst.shape

(4000, 3000, 3)

In [30]:

if cv2.contourArea(pos)<(0.15*x*y):
    pts1=pts2
else:
    pts1=sizee(pts1)
#pts1=np.float32(arr)
#pts2=sizee(pts2)


'\nif cv2.contourArea(pos)<(0.15*x*y):\n    pts1=pts2\nelse:\n    pts1=sizee(pts1)\n#pts1=np.float32(arr)\n#pts2=sizee(pts2)\n'

In [10]:
arr

[[148, 229], [218, 228], [148, 229], [219, 233]]

In [11]:
img==dst

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       ...,

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        ...,
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,

In [4]:
edge



array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
image= cv2.cvtColor(edge,cv2.COLOR_GRAY2BGR)


In [22]:
IMAGE

NameError: name 'IMAGE' is not defined

In [12]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [13]:
for x in range(len(image)): 
    for y in range(len(image[x])): 
        if int(image[x,y,1]) != 0:
            image[x,y]=[128,0,0]

In [29]:
image[0,0]

array([0, 0, 0], dtype=uint8)

In [31]:
len(image[x])

500

In [32]:
len(image)

667

In [14]:
cv2.imwrite("image.jpg",image)

True

In [ ]:
import cv2 as cv
# Load two images
#img1 = cv.imread('pic47.jpg')
img2 = cv.imread('image.jpg')
# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]
# Now create a mask of logo and create its inverse mask also
img2gray = cv.cvtColor(img2,cv.COLOR_BGR2GRAY)
ret, mask = cv.threshold(img2gray, 10, 255, cv.THRESH_BINARY)
mask_inv = cv.bitwise_not(mask)
# Now black-out the area of logo in ROI
img1_bg = cv.bitwise_and(roi,roi,mask = mask_inv)
# Take only region of logo from logo image.
img2_fg = cv.bitwise_and(img2,img2,mask = mask)
# Put logo in ROI and modify the main image
dst = cv.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst
cv.imshow('res',dst)
cv.waitKey(0)
cv.destroyAllWindows()
cv.imwrite("pic47blue.jpg",dst)

In [38]:
mask_inv

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [32]:
img2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [8]:
dst = cv.addWeighted(img1,0.1,img2,0.9,0)
cv.imshow('dst',dst)
cv.waitKey(0)
cv.destroyAllWindows()

In [42]:
img1.size

949650

In [43]:
img2.size

1000500

In [51]:
img1

array([[[111, 116, 115],
        [138, 143, 142],
        [146, 152, 151],
        ...,
        [ 87,  99, 111],
        [ 83,  96, 104],
        [ 80,  89,  98]],

       [[ 94,  99,  98],
        [121, 126, 125],
        [127, 133, 132],
        ...,
        [ 37,  50,  62],
        [ 40,  53,  61],
        [ 55,  66,  74]],

       [[ 89,  95,  94],
        [116, 121, 120],
        [123, 129, 128],
        ...,
        [ 26,  40,  52],
        [ 36,  49,  57],
        [ 73,  84,  92]],

       ...,

       [[  8,  28,  46],
        [ 16,  36,  54],
        [ 15,  34,  55],
        ...,
        [ 16,  35,  48],
        [ 37,  54,  63],
        [ 65,  78,  86]],

       [[ 26,  44,  61],
        [ 39,  57,  74],
        [ 21,  38,  57],
        ...,
        [ 29,  47,  59],
        [ 70,  87,  96],
        [105, 118, 126]],

       [[ 93, 109, 126],
        [103, 119, 136],
        [ 77,  92, 111],
        ...,
        [ 81,  98, 111],
        [122, 137, 146],
        [147, 160, 168]]

In [50]:
img2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [5]:
img1.size

1000500

In [6]:
img2.size

1000500

In [15]:
a=range(11,0,-2)

In [8]:
print(range(11,1,-2))

range(11, 1, -2)


In [10]:
a

range(11, 1, -2)

In [11]:
a[2]

7

In [12]:
a[1]

9

In [16]:
a[5]

1

In [14]:
a[4]

3